### ISSUE TITLE
End User

### ISSUE THREAD

**Issue by balaclava9** [lyoshenka/photoswipe-flickr#1]
Hi I'm just and end user trying to get this to work on my site. I entered the correct API key and set ID, but I still can't get demo.html to work. I'm currently using phpFlickr. Do you have a working site up somewhere with some of your pictures I can check out?

I noticed the slideshow you had on iceland on your site weren't working either:
http://i.grin.io/iceland/slideshow.html

Nice pictures in the regular flickr slideshow!

**Comment by lyoshenka** [comment]
The slideshow works fine for me. Maybe this is a browser-specific issues? What browser/OS are you using? Can you check the browser console to see if there are any JS errors there?

**Comment by balaclava9** [comment]
You're right on my iPad on iOS 8.4.1 it works fine. But under Yosemite 10.10.5 I'm having trouble. Firefox and Safari have a similar error

Here's from firefox 40.0.3, OS X 10.10.5:
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. slideshow.html

TypeError: item.o is undefined photoswipe-flickr.js:99:6

Will-change memory consumption is too high. Surface area covers 3913498 pixels, budget is the document surface area multiplied by 3 (1260630 pixels). All occurences of will-change in the document are ignored when over budget. slideshow.html

TypeError: item.o is undefined photoswipe-flickr.js:99:6

And from Safari Version 8.0.8 (10600.8.9) on 10.10.5:
[Error] TypeError: undefined is not an object (evaluating 'item['o'].src')
    (anonymous function) (photoswipe-flickr.js, line 99)
    Cb (photoswipe.min.js, line 4)
    setContent (photoswipe.min.js, line 4)
    init (photoswipe.min.js, line 4)
    gallerySetup (slideshow.html, line 85)
    (anonymous function) (photoswipe-flickr.js, line 170)
    (anonymous function) (photoswipe-flickr.js, line 30)
    global code (rest, line 1)
[Error] TypeError: undefined is not an object (evaluating 'item['o'].src')
    (anonymous function) (photoswipe-flickr.js, line 99)
    Cb (photoswipe.min.js, line 4)
    setContent (photoswipe.min.js, line 4)
    init (photoswipe.min.js, line 4)
    gallerySetup (slideshow.html, line 85)
    _init (photoswipe-flickr.js, line 138)
    photoswipeFlickr (photoswipe-flickr.js, line 4)
    onload (slideshow.html, line 93)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (favicon.ico, line 0)

**Comment by lyoshenka** [comment]
I'm not sure exactly what's going on. Can you try adding `console.log(item)` on line 96, right above where you get the error. Maybe that will give us more information.

**Comment by balaclava9** [comment]
thanks for checking! console.log(item) produced this: it looks like some of the object wasn't defined?

[Log] Object (photoswipe-flickr.js, line 96)
initialLayout: undefined
original_src: undefined
sizeData: Object
b: Object
h: undefined
src: undefined
w: undefined
**proto**: Object
c: Object
h: 640
src: "https://farm3.staticflickr.com/2949/15286149667_188ff012b0_c.jpg"
w: "800"
**proto**: Object
h: Object
h: 1280
src: "https://farm3.staticflickr.com/2949/15286149667_d80a6975db_h.jpg"
w: "1600"
**proto**: Object
k: Object
h: 1638
src: "https://farm3.staticflickr.com/2949/15286149667_f1e3fc44e4_k.jpg"
w: "2048"
**proto**: Object
m: Object
h: "400"
src: "https://farm3.staticflickr.com/2949/15286149667_188ff012b0.jpg"
w: "500"
**proto**: Object
n: Object
h: 256
src: "https://farm3.staticflickr.com/2949/15286149667_188ff012b0_n.jpg"
w: "320"
**proto**: Object
o: Object
h: undefined
src: undefined
w: undefined
**proto**: Object
z: Object
h: "512"
src: "https://farm3.staticflickr.com/2949/15286149667_188ff012b0_z.jpg"
w: "640"
**proto**: Object
**proto**: Object
**proto**: Object

**Comment by lyoshenka** [comment]
Hey, are you still having this issue? I've looked into it on and off over the last few weeks and I haven't been able to figure it out. My one guess is: maybe the images you're trying to use are not publicly-accessible? It looks like the links above are visible to me, but maybe that's because its a direct link to the image. Maybe if your images are private, the Flickr API won't return information about them?

**Comment by hugovk** [comment]
I think PR https://github.com/lyoshenka/photoswipe-flickr/pull/2 will fix this.

`[Error] TypeError: undefined is not an object (evaluating 'item['o'].src')`

It's trying `item['o'].src` but should be fetching `item.sizeData['o'].src`.

**Comment by lyoshenka** [comment]
please reopen this if you're still seeing this bug
